---
title: "tidy data 0924"
author: "Wurongyan Zhang"
date: "9/24/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
pulse_data = haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(bdi_score_bl:bdi_score_12m,
               names_to = "visit", values_to = "bdi") %>%
  mutate(visit = recode(visit, "bl" = "00m"))
#recode: this value should be another value
pulse_data

#cmd+shift+m
#%>% 

```

```{r}
#separate in litters

litters_data = 
  read_csv("./data_import_examples/FAS_litters.csv")
  janitor::clean_names(litters_data) %>% 
    separate(col = group, into = c("dose","day_of_dx"),3)
```

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)
pivot_wider(
  analysis_result,
  names_from = "time",
  values_from = "mean"
)
```

```{r}
fellowship_data = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
``` 


```{r}
lord_data = 
  bind_rows(fellowship_data, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words") %>% 
  mutate(race = str_to_lower(race)) %>% 
  select(movie, everything()
  )
```

#join data sets

```{r}
pup_data = 
  read_csv("./data_import_examples/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = 
  read_csv("./data_import_examples/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))

fas_data = 
  left_join(pup_data, litter_data, by = "litter_number")
fas_data
```














