---
title: "0926"
author: "Wurongyan Zhang"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggridges)
```

```{r}
weather_df = rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()

plot_weather = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) 

plot_weather + geom_point()
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.5) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
#alpha = transparency(0=transparent)
#se = turn CI off
#facet_grid = grid of individual panals
#.~name = name in columns
```

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(size = 2, se = FALSE) + 
  facet_grid(. ~ name)
```

take of geom points
```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) 
```


geom_hex(), geom_bin2d(), or geom_density2d()

```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()
```

```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_bin2d()
```

```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_density2d()
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmax)) + 
  geom_histogram()
```

position: dodge together, next to each other

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge", binwidth = 2)
```


alpha: transparency
adjust: it helps to try a few values.
geom_rug() : helpful way to show the raw data in addition to the density.

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .4, adjust = .5, color = "blue") +
  geom_rug()
```

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + geom_boxplot()
```

violin plot:

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  stat_summary(fun.y = median, geom = "point", color = "blue", size = 4)
```

ridge:

```{r}
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)
```

















