---
title: '1003'
author: "Wurongyan Zhang"
date: "10/3/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)

```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, date, month, everything())
```

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(n = n())
```

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n_obs = n(),
    n_days = n_distinct(date))
  
```

```{r}
weather_df %>%
  pull(name) %>% 
  table
```


# 2x2 table
```{r}
weather_df %>% 
  filter(name != "Waikiki_HA") %>% 
  mutate(cold = case_when(
    tmax < 5 ~"cold",
    tmax>=5 ~"not cold",
    TRUE ~ ""
  )) %>% 
  group_by(name, cold) %>% 
  summarize(count = n())

#or
weather_df %>% 
  mutate(cold = case_when(
    tmax < 5 ~ "cold",
    tmax >=5 ~ "not_cold",
    TRUE     ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  janitor::tabyl(name, cold)

```

# general summaries
```{r}
weather_df %>%
  group_by(month) %>%
  summarize(
    n=n(),
    mean_tmax = mean(tmax),
    mean_prec = mean(prcp, na.rm = TRUE),
    median_tmax = median(tmax),
    sd_tmax = sd(tmax))
```
```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(
    mean_tmax = mean(tmax),
    median_tmax = median(tmax))
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  ggplot(aes(x = month, y = mean_tmax, color = name)) + 
    geom_point() + geom_line() + 
    theme(legend.position = "bottom")
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) %>% 
  #show 1 digit
  knitr::kable(digits = 1)
```

# grouped mutate
```{r}
weather_df %>%
  group_by(name) %>%
  mutate(centered_tmax = tmax - mean(tmax))
```


```{r}
weather_df %>%
  group_by(name) %>%
  mutate(centered_tmax = tmax - mean(tmax)) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
    geom_point() 
```


```{r}
weather_df %>%
  group_by(name, month) %>%
  mutate(temp_ranking = min_rank(tmax))
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  filter(min_rank(tmax) < 2)
```

```{r}
weather_df %>%
  group_by(name, month) %>%
  filter(min_rank(desc(tmax)) < 4)
```

```{r}
# diff bw today and yesterday
weather_df %>%
  group_by(name) %>%
  mutate(temp_change = tmax - lag(tmax))
```

```{r}
weather_df %>%
  group_by(name) %>%
  mutate(temp_change = tmax - lag(tmax)) %>%
  summarize(temp_change_sd = sd(temp_change, na.rm = TRUE),
            temp_change_max = max(temp_change, na.rm = TRUE))
```

























