---
title: "classex"
author: "Wurongyan Zhang"
date: "9/17/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```
# 20190919

```{r}
#reads in data set

litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv", col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups = read_csv(file = "./data_import_examples/FAS_pups.csv", col_types = "ciiiii")
pups = janitor::clean_names(pups)
```

```{r}
select(litters_data, group, litter_number, gd0_weight, starts_with("pups"))

select(litters_data, litter_number, group, gd0_weight)

#starts with group, ends with gd of birth
select(litters_data, group:gd_of_birth)

#remove pups survive
select(litters_data,-pups_survive)
```

```{r}
#rename variable
select(litters_data, GROUP = group)
rename(litters_data, GROUP = group)
```


# filter

```{r}
filter(litters_data, group == "Con7")
filter(litters_data, gd_of_birth == "20")
filter(litters_data, gd_of_birth >="20")
filter(litters_data, group == "Con7", pups_born_alive < "6")
```

# or

```{r}
filter(litters_data, group == "Con7" | group == "Con8")
filter(litters_data, group %in% c("Con7", "Con8"))
filter(litters_data, gd0_weight + gd18_weight < 70)

```

# miss values
```{r}
#do not use
filter(litters_data, is.na(gd0_weight))

#use
drop_na(litters_data, gd0_weight)
```

```{r}
#mutate
mutate(litters_data, wt_gain = gd18_weight - gd0_weight, group = str_to_lower(group)) #to lower cases for group

```

# arrange
```{r}
head(arrange(litters_data, group, pups_born_alive),10)
#descending
arrange(litters_data, group, desc(pups_born_alive))
```

```{r}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names(dat = .) %>%
  select(.data = ., -pups_survive) %>%
  mutate(.data = .,
         wt_gain = gd18_weight - gd0_weight,
         group = str_to_lower(group)) %>%
  drop_na(data = ., wt_gain)

litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)

```


loads the pups data
cleans the variable names
filters the data to include only pups with sex 1
removes the PD ears variable
creates a variable that indicates whether PD pivot is 7 or more days
```{r}
pups = read_csv(file = "./data_import_examples/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  filter(sex == "1") %>%
  select(-pd_ears) %>%
  mutate(pivots = pd_pivot >= 7)
```











# 20190917

```{r}
litters_data = janitor::clean_names(litters_data)
names(litters_data)
```

```{r}
pups = read_csv(file = "./data_import_examples/FAS_pups.csv")
```

```{r}
skimr::skim(litters_data)
```

```{r}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv",
  skip = 10, col_names = FALSE)
```


```{r}
litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
```

```{r}
library(readxl)
mlb11_data = read_excel("data_import_examples/mlb11.xlsx", n_max = 20)
head(mlb11_data, 5)
```

```{r}
pups_base = read.csv("./data_import_examples/FAS_litters.csv")
pups_readr = read_csv("./data_import_examples/FAS_litters.csv")

View(pups_base)
View(pups_readr)

pups_base
pups_readr

pups_base$S
pups_readr$S
```


# 20190924

























